from __future__ import annotations

import copy
import os
from pathlib import Path

from .errors import ToolArgumentError, ToolNotRegisteredError, ToolRegistryError


TOOL_REGISTRY = {
    "g/check": {
        "namespace": "g",
        "action": "check",
        "module": "tools.workspace_tools",
        "function": "gmail_check",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gmail_check_result",
        "required_args": [],
        "optional_args": ["max_results"],
        "arg_types": {"max_results": "int"},
    },
    "messages/read_recent": {
        "namespace": "messages",
        "action": "read_recent",
        "module": "runtime.messages_tools",
        "function": "messages_read_recent",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "messages_read_recent_result",
        "required_args": ["thread_name"],
        "optional_args": ["limit", "runtime_root", "slowmo", "keep_open", "browser_user_data_dir", "browser_profile_dir", "browser_cdp_url"],
        "arg_types": {"limit": "int", "slowmo": "int", "keep_open": "bool"},
    },
    "g/send": {
        "namespace": "g",
        "action": "send",
        "module": "tools.workspace_tools",
        "function": "gmail_send",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gmail_send_result",
        "required_args": ["to", "subject", "body"],
        "optional_args": [],
        "arg_types": {},
    },
    "gmail/send": {
        "namespace": "gmail",
        "action": "send",
        "module": "runtime.gmail_send_tool",
        "function": "gmail_send_live_execute",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": True,
        "allow_live_side_effect": True,
        "live_guardrail": "gmail_send",
        "output_type": "gmail_send_result",
        "required_args": ["to", "subject", "body"],
        "optional_args": ["cc", "bcc", "attachments", "dry_run"],
        "arg_types": {"dry_run": "bool"},
    },
    "file/read_json": {
        "namespace": "file",
        "action": "read_json",
        "module": "runtime.file_tools",
        "function": "file_read_json",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_read_json_result",
        "required_args": ["path"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "file/write_json": {
        "namespace": "file",
        "action": "write_json",
        "module": "runtime.file_tools",
        "function": "file_write_json",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_write_json_result",
        "required_args": ["path", "data"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "file/list": {
        "namespace": "file",
        "action": "list",
        "module": "runtime.file_tools",
        "function": "file_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_list_result",
        "required_args": [],
        "optional_args": ["path", "runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "file/exists": {
        "namespace": "file",
        "action": "exists",
        "module": "runtime.file_tools",
        "function": "file_exists",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_exists_result",
        "required_args": ["path"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "cal/next": {
        "namespace": "cal",
        "action": "next",
        "module": "tools.workspace_tools",
        "function": "calendar_next",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_event_list",
        "required_args": [],
        "optional_args": ["max_results"],
        "arg_types": {"max_results": "int"},
    },
    "cal/search": {
        "namespace": "cal",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "calendar_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_event_list",
        "required_args": [],
        "optional_args": ["query", "days", "time_min", "time_max", "max_results"],
        "arg_types": {"days": "int", "max_results": "int"},
    },
    "cal/create": {
        "namespace": "cal",
        "action": "create",
        "module": "tools.workspace_tools",
        "function": "calendar_create",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_create_result",
        "required_args": ["title", "start", "end"],
        "optional_args": ["description", "location"],
        "arg_types": {},
    },
    "cal/remove": {
        "namespace": "cal",
        "action": "remove",
        "module": "tools.workspace_tools",
        "function": "calendar_remove",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_remove_result",
        "required_args": ["event_id"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/create": {
        "namespace": "sheet",
        "action": "create",
        "module": "tools.workspace_tools",
        "function": "sheet_create",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_create",
        "output_type": "sheet_create_result",
        "required_args": ["title"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/read": {
        "namespace": "sheet",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "sheet_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_rows",
        "required_args": ["spreadsheet_id", "range_name"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/write": {
        "namespace": "sheet",
        "action": "write",
        "module": "tools.workspace_tools",
        "function": "sheet_write",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_write",
        "output_type": "sheet_write_result",
        "required_args": ["spreadsheet_id", "range_name", "values_json"],
        "optional_args": ["mode"],
        "arg_types": {},
    },
    "wa/search": {
        "namespace": "wa",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "whatsapp_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_search_result",
        "required_args": ["chat"],
        "optional_args": [],
        "arg_types": {},
    },
    "wa/read": {
        "namespace": "wa",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "whatsapp_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_messages",
        "required_args": ["chat"],
        "optional_args": ["limit"],
        "arg_types": {"limit": "int"},
    },
    "wa/send": {
        "namespace": "wa",
        "action": "send",
        "module": "tools.workspace_tools",
        "function": "whatsapp_send",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_send_result",
        "required_args": ["chat"],
        "optional_args": ["message", "file_path", "caption", "kind"],
        "arg_types": {},
    },
    "customer/read": {
        "namespace": "customer",
        "action": "read",
        "module": "runtime.customer_tools",
        "function": "customer_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_read_result",
        "required_args": ["customer_id"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "sheet/read_range": {
        "namespace": "sheet",
        "action": "read_range",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_read_range",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_read_range_result",
        "required_args": ["spreadsheet_id", "range_name"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "sheet/prepare_write_rows": {
        "namespace": "sheet",
        "action": "prepare_write_rows",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_prepare_write_rows",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_write_rows_pending",
        "required_args": ["spreadsheet_id", "range_name", "rows"],
        "optional_args": ["mode"],
        "arg_types": {},
    },
    "sheet/write_rows": {
        "namespace": "sheet",
        "action": "write_rows",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_write_rows",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": True,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_write",
        "output_type": "sheet_write_rows_result",
        "required_args": ["spreadsheet_id", "range_name", "rows"],
        "optional_args": ["mode", "dry_run"],
        "arg_types": {},
    },
    "acct/load_payments": {
        "namespace": "acct",
        "action": "load_payments",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_payments",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_payments",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_orders": {
        "namespace": "acct",
        "action": "load_orders",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_orders",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_orders",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_invoices": {
        "namespace": "acct",
        "action": "load_invoices",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_invoices",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_invoices",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_ledger": {
        "namespace": "acct",
        "action": "load_ledger",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_ledger",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_ledger",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/build_recon_sheet_rows": {
        "namespace": "acct",
        "action": "build_recon_sheet_rows",
        "module": "runtime.accounting_tools",
        "function": "accounting_build_recon_sheet_rows",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "recon_sheet_rows",
        "required_args": ["reconciliation_result", "exception_summary"],
        "optional_args": ["frame_id"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "recon/match_payments": {
        "namespace": "recon",
        "action": "match_payments",
        "module": "runtime.reconciliation_tools",
        "function": "reconciliation_match_payments",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reconciliation_result",
        "required_args": ["payments", "orders", "invoices", "ledger_entries"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "recon/validate_result": {
        "namespace": "recon",
        "action": "validate_result",
        "module": "runtime.reconciliation_tools",
        "function": "reconciliation_validate_result",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reconciliation_validation",
        "required_args": ["reconciliation_result"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "customer/extract_order_ref": {
        "namespace": "customer",
        "action": "extract_order_ref",
        "module": "runtime.order_tools",
        "function": "order_extract_ref_from_text",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_ref_result",
        "required_args": ["message"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/order_context": {
        "namespace": "customer",
        "action": "order_context",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_context_result",
        "required_args": ["customer_id", "order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/build_status_context": {
        "namespace": "customer",
        "action": "build_status_context",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "status_context",
        "required_args": ["customer", "order", "shipment"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/validate_owns_order": {
        "namespace": "customer",
        "action": "validate_owns_order",
        "module": "runtime.customer_tools",
        "function": "customer_validate_owns_order",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "ownership_check",
        "required_args": ["customer", "order"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/validate_status_reply": {
        "namespace": "customer",
        "action": "validate_status_reply",
        "module": "runtime.message_tools",
        "function": "message_validate_customer_status_reply",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reply_validation",
        "required_args": ["reply", "order", "shipment"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/prepare_message_action": {
        "namespace": "customer",
        "action": "prepare_message_action",
        "module": "runtime.customer_tools",
        "function": "customer_prepare_message_action",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_message_action",
        "required_args": ["customer", "channel", "message"],
        "optional_args": [],
        "arg_types": {},
    },
    "customer/search": {
        "namespace": "customer",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "customer_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_list",
        "required_args": [],
        "optional_args": ["customer_id", "name", "status"],
        "arg_types": {},
    },
    "order/read": {
        "namespace": "order",
        "action": "read",
        "module": "runtime.order_tools",
        "function": "order_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_read_result",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order/search": {
        "namespace": "order",
        "action": "search",
        "module": "runtime.order_tools",
        "function": "order_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_list",
        "required_args": [],
        "optional_args": ["customer_id", "order_ref", "status"],
        "arg_types": {},
    },
    "order/extract_ref_from_text": {
        "namespace": "order",
        "action": "extract_ref_from_text",
        "module": "runtime.order_tools",
        "function": "order_extract_ref_from_text",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_ref_lookup",
        "required_args": ["text"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order/items_list": {
        "namespace": "order",
        "action": "items_list",
        "module": "runtime.order_tools",
        "function": "order_items_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_item_list",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
    },
    "order/validate_new": {
        "namespace": "order", "action": "validate_new",
        "module": "runtime.order_management_tools", "function": "order_validate_new",
        "side_effect": False, "requires_approval": False,
        "allow_live": True, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_validation_result",
        "required_args": ["customer_id", "items"], "optional_args": ["runtime_root"],
        "arg_types": {}, "dry_run_executes": True,
    },
    "order/prepare_stock_reservation": {
        "namespace": "order", "action": "prepare_stock_reservation",
        "module": "runtime.order_management_tools", "function": "order_prepare_stock_reservation",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "stock_reservation_prepare_result",
        "required_args": ["order_ref", "items"], "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "order/execute_stock_reservation": {
        "namespace": "order", "action": "execute_stock_reservation",
        "module": "runtime.order_management_tools", "function": "order_execute_stock_reservation",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "stock_reservation_execution_result",
        "required_args": ["order_ref"], "optional_args": ["reservation_lines", "dry_run", "runtime_root"],
        "arg_types": {"dry_run": "bool"},
    },
    "order/check_payment_status": {
        "namespace": "order", "action": "check_payment_status",
        "module": "runtime.order_management_tools", "function": "order_check_payment_status",
        "side_effect": False, "requires_approval": False,
        "allow_live": True, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_payment_status_result",
        "required_args": ["order_ref"], "optional_args": ["runtime_root"],
        "arg_types": {}, "dry_run_executes": True,
    },
    "order/prepare_release_paid_order": {
        "namespace": "order", "action": "prepare_release_paid_order",
        "module": "runtime.order_management_tools", "function": "order_prepare_release_paid_order",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_release_prepare_result",
        "required_args": ["order_ref"], "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "order/execute_release_paid_order": {
        "namespace": "order", "action": "execute_release_paid_order",
        "module": "runtime.order_management_tools", "function": "order_execute_release_paid_order",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_release_execution_result",
        "required_args": ["order_ref"], "optional_args": ["dry_run", "runtime_root"],
        "arg_types": {"dry_run": "bool"},
    },
    "order/detect_delayed_orders": {
        "namespace": "order", "action": "detect_delayed_orders",
        "module": "runtime.order_management_tools", "function": "order_detect_delayed_orders",
        "side_effect": False, "requires_approval": False,
        "allow_live": True, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "delayed_orders_result",
        "required_args": [], "optional_args": ["days_overdue", "runtime_root"],
        "arg_types": {"days_overdue": "int"}, "dry_run_executes": True,
    },
    "order/prepare_shipment_status_update": {
        "namespace": "order", "action": "prepare_shipment_status_update",
        "module": "runtime.order_management_tools", "function": "order_prepare_shipment_status_update",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "shipment_update_prepare_result",
        "required_args": ["order_ref", "shipment_status"], "optional_args": ["tracking_ref", "runtime_root"],
        "arg_types": {},
    },
    "order/execute_shipment_status_update": {
        "namespace": "order", "action": "execute_shipment_status_update",
        "module": "runtime.order_management_tools", "function": "order_execute_shipment_status_update",
        "side_effect": True, "requires_approval": True,
        "allow_live": False, "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "shipment_update_execution_result",
        "required_args": ["order_ref", "shipment_status"], "optional_args": ["tracking_ref", "dry_run", "runtime_root"],
        "arg_types": {"dry_run": "bool"},
    },
    "shipment/read": {
        "namespace": "shipment",
        "action": "read",
        "module": "runtime.shipment_tools",
        "function": "shipment_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "shipment_read_result",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "payment/read_by_order": {
        "namespace": "payment",
        "action": "read_by_order",
        "module": "runtime.payment_tools",
        "function": "payment_read_by_order",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "payment_record",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
    },
    "inventory/read": {
        "namespace": "inventory",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "inventory_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "inventory_record",
        "required_args": ["sku"],
        "optional_args": [],
        "arg_types": {},
    },
    "inventory/search_low_stock": {
        "namespace": "inventory",
        "action": "search_low_stock",
        "module": "runtime.procurement_tools",
        "function": "inventory_search_low_stock",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "low_stock_result",
        "required_args": [],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "inventory/filter_reorder_candidates": {
        "namespace": "inventory",
        "action": "filter_reorder_candidates",
        "module": "runtime.procurement_tools",
        "function": "inventory_filter_reorder_candidates",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reorder_candidates",
        "required_args": ["items"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/check_duplicate_open": {
        "namespace": "po",
        "action": "check_duplicate_open",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_check_duplicate_open",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "duplicate_po_check",
        "required_args": ["candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "supplier/select_for_sku": {
        "namespace": "supplier",
        "action": "select_for_sku",
        "module": "runtime.procurement_tools",
        "function": "supplier_select_for_sku",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "selected_supplier",
        "required_args": ["candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/build_draft": {
        "namespace": "po",
        "action": "build_draft",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_build_draft",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "draft_po",
        "required_args": ["supplier", "candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/validate_draft": {
        "namespace": "po",
        "action": "validate_draft",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_validate_draft",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "po_validation",
        "required_args": ["draft_po"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "message/validate_customer_status_reply": {
        "namespace": "message",
        "action": "validate_customer_status_reply",
        "module": "runtime.message_tools",
        "function": "message_validate_customer_status_reply",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reply_validation",
        "required_args": ["draft_reply", "order_context"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "message/validate_supplier_reorder_message": {
        "namespace": "message",
        "action": "validate_supplier_reorder_message",
        "module": "runtime.message_tools",
        "function": "message_validate_supplier_reorder_message",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_message_validation",
        "required_args": ["supplier_message", "draft_po"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "supplier/prepare_message_action": {
        "namespace": "supplier",
        "action": "prepare_message_action",
        "module": "runtime.procurement_tools",
        "function": "supplier_prepare_message_action",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_message_pending_action",
        "required_args": ["supplier", "draft_po", "message"],
        "optional_args": [],
        "arg_types": {},
    },
    "supplier/send_message": {
        "namespace": "supplier",
        "action": "send_message",
        "module": "runtime.procurement_tools",
        "function": "supplier_send_message",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_send_result",
        "required_args": ["to", "subject", "body"],
        "optional_args": ["draft_po", "dry_run", "runtime_root"],
        "arg_types": {},
    },
    "supplier/read": {
        "namespace": "supplier",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "supplier_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_record",
        "required_args": ["supplier_id"],
        "optional_args": [],
        "arg_types": {},
    },
    "supplier/search_active": {
        "namespace": "supplier",
        "action": "search_active",
        "module": "tools.workspace_tools",
        "function": "supplier_search_active",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_list",
        "required_args": [],
        "optional_args": [],
        "arg_types": {},
    },
    "purchase_order/search_open_by_sku": {
        "namespace": "purchase_order",
        "action": "search_open_by_sku",
        "module": "tools.workspace_tools",
        "function": "purchase_order_search_open_by_sku",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "purchase_order_list",
        "required_args": ["sku"],
        "optional_args": [],
        "arg_types": {},
    },
    "po/read": {
        "namespace": "po",
        "action": "read",
        "module": "runtime.supplier_invoice_tools",
        "function": "po_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "purchase_order_result",
        "required_args": ["po_ref"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "receipt/read_by_po": {
        "namespace": "receipt",
        "action": "read_by_po",
        "module": "runtime.supplier_invoice_tools",
        "function": "receipt_read_by_po",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "goods_receipt_result",
        "required_args": ["po_ref"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/read": {
        "namespace": "supplier_invoice",
        "action": "read",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_result",
        "required_args": ["invoice_ref"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/check_duplicate": {
        "namespace": "supplier_invoice",
        "action": "check_duplicate",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_check_duplicate",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_duplicate_check_result",
        "required_args": ["supplier_id", "supplier_invoice_number"],
        "optional_args": ["invoice_ref", "runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/match_three_way": {
        "namespace": "supplier_invoice",
        "action": "match_three_way",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_match_three_way",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_match_result",
        "required_args": ["invoice", "purchase_order", "receipts"],
        "optional_args": ["tolerance_amount", "tolerance_percent", "runtime_root"],
        "arg_types": {"tolerance_amount": "float", "tolerance_percent": "float"},
    },
    "supplier_invoice/prepare_match_run_write": {
        "namespace": "supplier_invoice",
        "action": "prepare_match_run_write",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_prepare_match_run_write",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_match_write_prepare_result",
        "required_args": ["match_result"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/prepare_ledger_write": {
        "namespace": "supplier_invoice",
        "action": "prepare_ledger_write",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_prepare_ledger_write",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_ledger_write_prepare_result",
        "required_args": ["invoice", "match_result"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/execute_ledger_write": {
        "namespace": "supplier_invoice",
        "action": "execute_ledger_write",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_execute_ledger_write",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_ledger_write_execution_result",
        "required_args": ["ledger_rows"],
        "optional_args": ["dry_run", "runtime_root"],
        "arg_types": {},
    },
    "supplier_invoice/build_exception_report": {
        "namespace": "supplier_invoice",
        "action": "build_exception_report",
        "module": "runtime.supplier_invoice_tools",
        "function": "supplier_invoice_build_exception_report",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_exception_report_result",
        "required_args": ["invoice", "purchase_order", "receipts", "match_result"],
        "optional_args": ["exception_summary", "runtime_root"],
        "arg_types": {},
    },
    "test/echo": {
        "namespace": "test",
        "action": "echo",
        "module": "runtime.test_tools",
        "function": "echo",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "test_echo_result",
        "required_args": [],
        "optional_args": ["message", "event_id"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order_context/build": {
        "namespace": "order_context",
        "action": "build",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_context_build_result",
        "required_args": ["customer", "order", "shipment"],
        "optional_args": ["payment"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "gb/list": {
        "namespace": "gb",
        "action": "list",
        "module": "tools.gobook_tools",
        "function": "rpa_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_booking_list",
        "required_args": [],
        "optional_args": ["slowmo"],
        "arg_types": {"slowmo": "int"},
    },
    "gb/open_courts": {
        "namespace": "gb",
        "action": "open_courts",
        "module": "tools.gobook_tools",
        "function": "rpa_open_courts",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_open_court_list",
        "required_args": ["date", "start", "end"],
        "optional_args": ["slowmo"],
        "arg_types": {"slowmo": "int"},
    },
    "gb/book": {
        "namespace": "gb",
        "action": "book",
        "module": "tools.gobook_tools",
        "function": "rpa_book",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_booking_result",
        "required_args": ["date", "time_value", "court"],
        "optional_args": ["confirm", "slowmo"],
        "arg_types": {"confirm": "bool", "slowmo": "int"},
    },
    "gb/cancel": {
        "namespace": "gb",
        "action": "cancel",
        "module": "tools.gobook_tools",
        "function": "rpa_cancel",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_cancel_result",
        "required_args": ["date", "time_value", "court"],
        "optional_args": ["confirm", "slowmo"],
        "arg_types": {"confirm": "bool", "slowmo": "int"},
    },
}


_INVOICEOPS_TOOL_REGISTRY = {
    "invoiceops/read_invoice_file": {
        "namespace": "invoiceops",
        "action": "read_invoice_file",
        "module": "runtime.invoiceops_reader_tools",
        "function": "invoiceops_read_invoice_file",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_raw_invoice_text",
        "required_args": ["path"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/extract_invoice_fields": {
        "namespace": "invoiceops",
        "action": "extract_invoice_fields",
        "module": "runtime.invoiceops_extraction_tools",
        "function": "invoiceops_extract_invoice_fields",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_invoice",
        "required_args": ["raw_text"],
        "optional_args": ["source_ref"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/validate_invoice_fields": {
        "namespace": "invoiceops",
        "action": "validate_invoice_fields",
        "module": "runtime.invoiceops_extraction_tools",
        "function": "invoiceops_validate_invoice_fields",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_invoice_validation",
        "required_args": ["invoice"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_supplier_master": {
        "namespace": "invoiceops",
        "action": "read_supplier_master",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_supplier_master",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_po_register": {
        "namespace": "invoiceops",
        "action": "read_po_register",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_po_register",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_receipt_register": {
        "namespace": "invoiceops",
        "action": "read_receipt_register",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_receipt_register",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_invoice_register": {
        "namespace": "invoiceops",
        "action": "read_invoice_register",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_invoice_register",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_ledger": {
        "namespace": "invoiceops",
        "action": "read_ledger",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_ledger",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/read_exception_register": {
        "namespace": "invoiceops",
        "action": "read_exception_register",
        "module": "runtime.invoiceops_sheet_tools",
        "function": "invoiceops_read_exception_register",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_sheet_rows",
        "required_args": [],
        "optional_args": ["spreadsheet_id", "fixture_mode", "_fixture_dir"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/check_duplicate_invoice": {
        "namespace": "invoiceops",
        "action": "check_duplicate_invoice",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_check_duplicate_invoice",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_check",
        "required_args": ["invoice", "invoice_register"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/lookup_purchase_order": {
        "namespace": "invoiceops",
        "action": "lookup_purchase_order",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_lookup_purchase_order",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_check",
        "required_args": ["invoice", "po_register"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/lookup_goods_receipt": {
        "namespace": "invoiceops",
        "action": "lookup_goods_receipt",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_lookup_goods_receipt",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_check",
        "required_args": ["invoice", "receipt_register"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/check_totals": {
        "namespace": "invoiceops",
        "action": "check_totals",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_check_totals",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_check",
        "required_args": ["invoice", "purchase_order"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/check_tax": {
        "namespace": "invoiceops",
        "action": "check_tax",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_check_tax",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_check",
        "required_args": ["invoice"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/match_three_way": {
        "namespace": "invoiceops",
        "action": "match_three_way",
        "module": "runtime.invoiceops_matching_tools",
        "function": "invoiceops_match_three_way",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_match_result",
        "required_args": ["invoice", "purchase_order", "goods_receipt"],
        "optional_args": ["invoice_register"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/classify_exceptions": {
        "namespace": "invoiceops",
        "action": "classify_exceptions",
        "module": "runtime.invoiceops_exception_tools",
        "function": "invoiceops_classify_exceptions",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_exception_classification",
        "required_args": ["match_result", "invoice"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/search_po_fallback": {
        "namespace": "invoiceops",
        "action": "search_po_fallback",
        "module": "runtime.invoiceops_exception_tools",
        "function": "invoiceops_search_po_fallback",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_fallback_result",
        "required_args": ["invoice", "po_register"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/search_receipt_fallback": {
        "namespace": "invoiceops",
        "action": "search_receipt_fallback",
        "module": "runtime.invoiceops_exception_tools",
        "function": "invoiceops_search_receipt_fallback",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_fallback_result",
        "required_args": ["invoice", "receipt_register"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/search_supplier_fallback": {
        "namespace": "invoiceops",
        "action": "search_supplier_fallback",
        "module": "runtime.invoiceops_exception_tools",
        "function": "invoiceops_search_supplier_fallback",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_fallback_result",
        "required_args": ["invoice", "supplier_master"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_exception_action_plan": {
        "namespace": "invoiceops",
        "action": "build_exception_action_plan",
        "module": "runtime.invoiceops_exception_tools",
        "function": "invoiceops_build_exception_action_plan",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_exception_action_plan",
        "required_args": ["invoice", "exceptions"],
        "optional_args": ["fallback_results"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/prepare_invoice_register_write": {
        "namespace": "invoiceops",
        "action": "prepare_invoice_register_write",
        "module": "runtime.invoiceops_write_tools",
        "function": "invoiceops_prepare_invoice_register_write",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_prepared_write",
        "required_args": ["invoice"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/prepare_match_register_write": {
        "namespace": "invoiceops",
        "action": "prepare_match_register_write",
        "module": "runtime.invoiceops_write_tools",
        "function": "invoiceops_prepare_match_register_write",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_prepared_write",
        "required_args": ["match_result"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/prepare_exception_register_write": {
        "namespace": "invoiceops",
        "action": "prepare_exception_register_write",
        "module": "runtime.invoiceops_write_tools",
        "function": "invoiceops_prepare_exception_register_write",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_prepared_write",
        "required_args": ["exceptions"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/prepare_ledger_write": {
        "namespace": "invoiceops",
        "action": "prepare_ledger_write",
        "module": "runtime.invoiceops_write_tools",
        "function": "invoiceops_prepare_ledger_write",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_prepared_write",
        "required_args": ["ledger_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/prepare_rollback_plan": {
        "namespace": "invoiceops",
        "action": "prepare_rollback_plan",
        "module": "runtime.invoiceops_write_tools",
        "function": "invoiceops_prepare_rollback_plan",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_rollback_plan",
        "required_args": ["prepared_write"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_match_report": {
        "namespace": "invoiceops",
        "action": "build_match_report",
        "module": "runtime.invoiceops_report_tools",
        "function": "invoiceops_build_match_report",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_report",
        "required_args": ["invoice", "match_result"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_exception_report": {
        "namespace": "invoiceops",
        "action": "build_exception_report",
        "module": "runtime.invoiceops_report_tools",
        "function": "invoiceops_build_exception_report",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_report",
        "required_args": ["invoice", "exceptions"],
        "optional_args": ["action_plan"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_ledger_posting_summary": {
        "namespace": "invoiceops",
        "action": "build_ledger_posting_summary",
        "module": "runtime.invoiceops_report_tools",
        "function": "invoiceops_build_ledger_posting_summary",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_report",
        "required_args": ["invoice", "ledger_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_rollback_summary": {
        "namespace": "invoiceops",
        "action": "build_rollback_summary",
        "module": "runtime.invoiceops_report_tools",
        "function": "invoiceops_build_rollback_summary",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_report",
        "required_args": ["prepared_writes"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "invoiceops/build_evidence_bundle": {
        "namespace": "invoiceops",
        "action": "build_evidence_bundle",
        "module": "runtime.invoiceops_report_tools",
        "function": "invoiceops_build_evidence_bundle",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "invoiceops_report",
        "required_args": ["invoice"],
        "optional_args": ["match_result", "exceptions", "prepared_writes"],
        "arg_types": {},
        "dry_run_executes": True,
    },
}

TOOL_REGISTRY.update(_INVOICEOPS_TOOL_REGISTRY)


BUILTIN_LEGACY_TOOL_REGISTRY = copy.deepcopy(TOOL_REGISTRY)
BUILTIN_TOOL_REGISTRY = BUILTIN_LEGACY_TOOL_REGISTRY


def build_tool_registry(
    *,
    include_migrated_toolpacks: bool = True,
    include_external: bool = True,
    include_legacy_fallback: bool = True,
    config_path: str | Path = "config/enabled_toolpacks.json",
) -> dict[str, dict]:
    registry: dict[str, dict] = {}

    if include_migrated_toolpacks:
        from src.tool_registry_compat import assert_registry_compatibility, build_compatibility_registry

        migrated_registry = build_compatibility_registry()
        assert_registry_compatibility(BUILTIN_LEGACY_TOOL_REGISTRY, migrated_registry)
        registry.update(_decorate_registry(migrated_registry, source="migrated_toolpack"))

    if include_external:
        from src.toolpack_loader import build_external_tool_registry

        external_registry = build_external_tool_registry(config_path=config_path)
        for key, spec in external_registry.items():
            if key in registry or key in BUILTIN_LEGACY_TOOL_REGISTRY:
                raise ToolRegistryError(f"External tool cannot override built-in tool: {key}")
            registry[key] = _decorate_tool_spec(spec, source=str(spec.get("source", "external_toolpack")))

    if include_legacy_fallback:
        for key, spec in BUILTIN_LEGACY_TOOL_REGISTRY.items():
            if key in registry:
                continue
            registry[key] = _decorate_tool_spec(spec, source="legacy_fallback")

    return registry


def tool_key(namespace: str, action: str) -> str:
    return f"{namespace}/{action}"


def get_tool_spec(namespace: str, action: str) -> dict:
    key = tool_key(namespace, action)
    try:
        return TOOL_REGISTRY[key]
    except KeyError as exc:
        raise ToolNotRegisteredError(f"Tool is not registered: {key}") from exc


def is_registered_tool(namespace: str, action: str) -> bool:
    return tool_key(namespace, action) in TOOL_REGISTRY


def validate_tool_args(tool_spec: dict, args: dict[str, object]) -> None:
    required_args = tool_spec.get("required_args", [])
    missing = [name for name in required_args if name not in args]
    if missing:
        raise ToolArgumentError(f"Missing required tool arguments: {', '.join(missing)}")


def coerce_tool_args(tool_spec: dict, args: dict[str, str]) -> dict[str, object]:
    coerced: dict[str, object] = {}
    arg_types = tool_spec.get("arg_types", {})
    for key, value in args.items():
        coercion_type = arg_types.get(key)
        if coercion_type == "int":
            coerced[key] = _coerce_int(key, value)
        elif coercion_type == "bool":
            coerced[key] = _coerce_bool(key, value)
        else:
            coerced[key] = value
    return coerced


def _coerce_int(key: str, value: object) -> int:
    if isinstance(value, bool):
        raise ToolArgumentError(f"Argument {key} must be an integer.")
    if isinstance(value, int):
        return value
    if not isinstance(value, str):
        raise ToolArgumentError(f"Argument {key} must be an integer.")
    try:
        return int(value)
    except ValueError as exc:
        raise ToolArgumentError(f"Argument {key} must be an integer.") from exc


def _coerce_bool(key: str, value: object) -> bool:
    if isinstance(value, bool):
        return value
    if not isinstance(value, str):
        raise ToolArgumentError(f"Argument {key} must be a boolean.")
    lowered = value.strip().lower()
    if lowered in {"true", "1", "yes", "on"}:
        return True
    if lowered in {"false", "0", "no", "off"}:
        return False
    raise ToolArgumentError(f"Argument {key} must be a boolean.")


def _decorate_registry(registry: dict[str, dict], *, source: str) -> dict[str, dict]:
    return {key: _decorate_tool_spec(spec, source=source) for key, spec in registry.items()}


def _decorate_tool_spec(spec: dict, *, source: str) -> dict:
    decorated = dict(spec)
    decorated.setdefault("source", source)
    decorated.setdefault("toolpack_id", "")
    decorated.setdefault("toolpack_name", "")
    decorated.setdefault("toolpack_version", "")
    decorated.setdefault("toolpack_path", "")
    decorated.setdefault("toolpack_core_or_optional", "core")
    decorated.setdefault("toolpack_classification", decorated.get("toolpack_core_or_optional", "core"))
    decorated.setdefault("enabled_environments", [])
    decorated.setdefault("governance_required", False)
    decorated.setdefault("toolpack_registered", source != "legacy_fallback")
    return decorated


TOOL_REGISTRY = build_tool_registry(include_migrated_toolpacks=True, include_external=True, include_legacy_fallback=True)


def register_optional_absa_tools(registry: dict[str, dict] | None = None) -> None:
    if os.environ.get("ENABLE_OPTIONAL_RPA_TOOLS", "").strip().lower() not in {"1", "true", "yes", "on"}:
        return
    target = registry if registry is not None else TOOL_REGISTRY
    from optional_tools.rpa.google_messages_absa.registry import register_tools

    register_tools(target)


register_optional_absa_tools()
