from __future__ import annotations

import copy
import os

from .errors import ToolArgumentError, ToolNotRegisteredError, ToolRegistryError


TOOL_REGISTRY = {
    "g/check": {
        "namespace": "g",
        "action": "check",
        "module": "tools.workspace_tools",
        "function": "gmail_check",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gmail_check_result",
        "required_args": [],
        "optional_args": ["max_results"],
        "arg_types": {"max_results": "int"},
    },
    "messages/read_recent": {
        "namespace": "messages",
        "action": "read_recent",
        "module": "runtime.messages_tools",
        "function": "messages_read_recent",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "messages_read_recent_result",
        "required_args": ["thread_name"],
        "optional_args": ["limit", "runtime_root", "slowmo", "keep_open", "browser_user_data_dir", "browser_profile_dir", "browser_cdp_url"],
        "arg_types": {"limit": "int", "slowmo": "int", "keep_open": "bool"},
    },
    "g/send": {
        "namespace": "g",
        "action": "send",
        "module": "tools.workspace_tools",
        "function": "gmail_send",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gmail_send_result",
        "required_args": ["to", "subject", "body"],
        "optional_args": [],
        "arg_types": {},
    },
    "file/read_json": {
        "namespace": "file",
        "action": "read_json",
        "module": "runtime.file_tools",
        "function": "file_read_json",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_read_json_result",
        "required_args": ["path"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "file/write_json": {
        "namespace": "file",
        "action": "write_json",
        "module": "runtime.file_tools",
        "function": "file_write_json",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_write_json_result",
        "required_args": ["path", "data"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
    },
    "file/list": {
        "namespace": "file",
        "action": "list",
        "module": "runtime.file_tools",
        "function": "file_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_list_result",
        "required_args": [],
        "optional_args": ["path", "runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "file/exists": {
        "namespace": "file",
        "action": "exists",
        "module": "runtime.file_tools",
        "function": "file_exists",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "file_exists_result",
        "required_args": ["path"],
        "optional_args": ["runtime_root"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "cal/next": {
        "namespace": "cal",
        "action": "next",
        "module": "tools.workspace_tools",
        "function": "calendar_next",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_event_list",
        "required_args": [],
        "optional_args": ["max_results"],
        "arg_types": {"max_results": "int"},
    },
    "cal/search": {
        "namespace": "cal",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "calendar_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_event_list",
        "required_args": [],
        "optional_args": ["query", "days", "time_min", "time_max", "max_results"],
        "arg_types": {"days": "int", "max_results": "int"},
    },
    "cal/create": {
        "namespace": "cal",
        "action": "create",
        "module": "tools.workspace_tools",
        "function": "calendar_create",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_create_result",
        "required_args": ["title", "start", "end"],
        "optional_args": ["description", "location"],
        "arg_types": {},
    },
    "cal/remove": {
        "namespace": "cal",
        "action": "remove",
        "module": "tools.workspace_tools",
        "function": "calendar_remove",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "calendar_remove_result",
        "required_args": ["event_id"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/create": {
        "namespace": "sheet",
        "action": "create",
        "module": "tools.workspace_tools",
        "function": "sheet_create",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_create",
        "output_type": "sheet_create_result",
        "required_args": ["title"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/read": {
        "namespace": "sheet",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "sheet_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_rows",
        "required_args": ["spreadsheet_id", "range_name"],
        "optional_args": [],
        "arg_types": {},
    },
    "sheet/write": {
        "namespace": "sheet",
        "action": "write",
        "module": "tools.workspace_tools",
        "function": "sheet_write",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_write",
        "output_type": "sheet_write_result",
        "required_args": ["spreadsheet_id", "range_name", "values_json"],
        "optional_args": ["mode"],
        "arg_types": {},
    },
    "wa/search": {
        "namespace": "wa",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "whatsapp_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_search_result",
        "required_args": ["chat"],
        "optional_args": [],
        "arg_types": {},
    },
    "wa/read": {
        "namespace": "wa",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "whatsapp_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_messages",
        "required_args": ["chat"],
        "optional_args": ["limit"],
        "arg_types": {"limit": "int"},
    },
    "wa/send": {
        "namespace": "wa",
        "action": "send",
        "module": "tools.workspace_tools",
        "function": "whatsapp_send",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "whatsapp_send_result",
        "required_args": ["chat"],
        "optional_args": ["message", "file_path", "caption", "kind"],
        "arg_types": {},
    },
    "customer/read": {
        "namespace": "customer",
        "action": "read",
        "module": "runtime.customer_tools",
        "function": "customer_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_read_result",
        "required_args": ["customer_id"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "sheet/read_range": {
        "namespace": "sheet",
        "action": "read_range",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_read_range",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_read_range_result",
        "required_args": ["spreadsheet_id", "range_name"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "sheet/prepare_write_rows": {
        "namespace": "sheet",
        "action": "prepare_write_rows",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_prepare_write_rows",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "sheet_write_rows_pending",
        "required_args": ["spreadsheet_id", "range_name", "rows"],
        "optional_args": ["mode"],
        "arg_types": {},
    },
    "sheet/write_rows": {
        "namespace": "sheet",
        "action": "write_rows",
        "module": "runtime.google_sheet_tools",
        "function": "sheet_write_rows",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": True,
        "allow_live_side_effect": True,
        "live_guardrail": "sheet_write",
        "output_type": "sheet_write_rows_result",
        "required_args": ["spreadsheet_id", "range_name", "rows"],
        "optional_args": ["mode", "dry_run"],
        "arg_types": {},
    },
    "acct/load_payments": {
        "namespace": "acct",
        "action": "load_payments",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_payments",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_payments",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_orders": {
        "namespace": "acct",
        "action": "load_orders",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_orders",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_orders",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_invoices": {
        "namespace": "acct",
        "action": "load_invoices",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_invoices",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_invoices",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/load_ledger": {
        "namespace": "acct",
        "action": "load_ledger",
        "module": "runtime.accounting_tools",
        "function": "accounting_load_ledger",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "accounting_ledger",
        "required_args": ["sheet_rows"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "acct/build_recon_sheet_rows": {
        "namespace": "acct",
        "action": "build_recon_sheet_rows",
        "module": "runtime.accounting_tools",
        "function": "accounting_build_recon_sheet_rows",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "recon_sheet_rows",
        "required_args": ["reconciliation_result", "exception_summary"],
        "optional_args": ["frame_id"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "recon/match_payments": {
        "namespace": "recon",
        "action": "match_payments",
        "module": "runtime.reconciliation_tools",
        "function": "reconciliation_match_payments",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reconciliation_result",
        "required_args": ["payments", "orders", "invoices", "ledger_entries"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "recon/validate_result": {
        "namespace": "recon",
        "action": "validate_result",
        "module": "runtime.reconciliation_tools",
        "function": "reconciliation_validate_result",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reconciliation_validation",
        "required_args": ["reconciliation_result"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "customer/extract_order_ref": {
        "namespace": "customer",
        "action": "extract_order_ref",
        "module": "runtime.order_tools",
        "function": "order_extract_ref_from_text",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_ref_result",
        "required_args": ["message"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/order_context": {
        "namespace": "customer",
        "action": "order_context",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_context_result",
        "required_args": ["customer_id", "order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/build_status_context": {
        "namespace": "customer",
        "action": "build_status_context",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "status_context",
        "required_args": ["customer", "order", "shipment"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/validate_owns_order": {
        "namespace": "customer",
        "action": "validate_owns_order",
        "module": "runtime.customer_tools",
        "function": "customer_validate_owns_order",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "ownership_check",
        "required_args": ["customer", "order"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/validate_status_reply": {
        "namespace": "customer",
        "action": "validate_status_reply",
        "module": "runtime.message_tools",
        "function": "message_validate_customer_status_reply",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reply_validation",
        "required_args": ["reply", "order", "shipment"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
        "failure_state": "FAILED_VALIDATION",
    },
    "customer/prepare_message_action": {
        "namespace": "customer",
        "action": "prepare_message_action",
        "module": "runtime.customer_tools",
        "function": "customer_prepare_message_action",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_message_action",
        "required_args": ["customer", "channel", "message"],
        "optional_args": [],
        "arg_types": {},
    },
    "customer/search": {
        "namespace": "customer",
        "action": "search",
        "module": "tools.workspace_tools",
        "function": "customer_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "customer_list",
        "required_args": [],
        "optional_args": ["customer_id", "name", "status"],
        "arg_types": {},
    },
    "order/read": {
        "namespace": "order",
        "action": "read",
        "module": "runtime.order_tools",
        "function": "order_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_read_result",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order/search": {
        "namespace": "order",
        "action": "search",
        "module": "runtime.order_tools",
        "function": "order_search",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_list",
        "required_args": [],
        "optional_args": ["customer_id", "order_ref", "status"],
        "arg_types": {},
    },
    "order/extract_ref_from_text": {
        "namespace": "order",
        "action": "extract_ref_from_text",
        "module": "runtime.order_tools",
        "function": "order_extract_ref_from_text",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_ref_lookup",
        "required_args": ["text"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order/items_list": {
        "namespace": "order",
        "action": "items_list",
        "module": "runtime.order_tools",
        "function": "order_items_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_item_list",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
    },
    "shipment/read": {
        "namespace": "shipment",
        "action": "read",
        "module": "runtime.shipment_tools",
        "function": "shipment_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "shipment_read_result",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "payment/read_by_order": {
        "namespace": "payment",
        "action": "read_by_order",
        "module": "runtime.payment_tools",
        "function": "payment_read_by_order",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "payment_record",
        "required_args": ["order_ref"],
        "optional_args": [],
        "arg_types": {},
    },
    "inventory/read": {
        "namespace": "inventory",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "inventory_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "inventory_record",
        "required_args": ["sku"],
        "optional_args": [],
        "arg_types": {},
    },
    "inventory/search_low_stock": {
        "namespace": "inventory",
        "action": "search_low_stock",
        "module": "runtime.procurement_tools",
        "function": "inventory_search_low_stock",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "low_stock_result",
        "required_args": [],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "inventory/filter_reorder_candidates": {
        "namespace": "inventory",
        "action": "filter_reorder_candidates",
        "module": "runtime.procurement_tools",
        "function": "inventory_filter_reorder_candidates",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reorder_candidates",
        "required_args": ["items"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/check_duplicate_open": {
        "namespace": "po",
        "action": "check_duplicate_open",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_check_duplicate_open",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "duplicate_po_check",
        "required_args": ["candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "supplier/select_for_sku": {
        "namespace": "supplier",
        "action": "select_for_sku",
        "module": "runtime.procurement_tools",
        "function": "supplier_select_for_sku",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "selected_supplier",
        "required_args": ["candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/build_draft": {
        "namespace": "po",
        "action": "build_draft",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_build_draft",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "draft_po",
        "required_args": ["supplier", "candidates"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "po/validate_draft": {
        "namespace": "po",
        "action": "validate_draft",
        "module": "runtime.procurement_tools",
        "function": "purchase_order_validate_draft",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "po_validation",
        "required_args": ["draft_po"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "message/validate_customer_status_reply": {
        "namespace": "message",
        "action": "validate_customer_status_reply",
        "module": "runtime.message_tools",
        "function": "message_validate_customer_status_reply",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "reply_validation",
        "required_args": ["draft_reply", "order_context"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "message/validate_supplier_reorder_message": {
        "namespace": "message",
        "action": "validate_supplier_reorder_message",
        "module": "runtime.message_tools",
        "function": "message_validate_supplier_reorder_message",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_message_validation",
        "required_args": ["supplier_message", "draft_po"],
        "optional_args": [],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "supplier/prepare_message_action": {
        "namespace": "supplier",
        "action": "prepare_message_action",
        "module": "runtime.procurement_tools",
        "function": "supplier_prepare_message_action",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_message_pending_action",
        "required_args": ["supplier", "draft_po", "message"],
        "optional_args": [],
        "arg_types": {},
    },
    "supplier/send_message": {
        "namespace": "supplier",
        "action": "send_message",
        "module": "runtime.procurement_tools",
        "function": "supplier_send_message",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_send_result",
        "required_args": ["to", "subject", "body"],
        "optional_args": ["draft_po", "dry_run", "runtime_root"],
        "arg_types": {},
    },
    "supplier/read": {
        "namespace": "supplier",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "supplier_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_record",
        "required_args": ["supplier_id"],
        "optional_args": [],
        "arg_types": {},
    },
    "supplier/search_active": {
        "namespace": "supplier",
        "action": "search_active",
        "module": "tools.workspace_tools",
        "function": "supplier_search_active",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_list",
        "required_args": [],
        "optional_args": [],
        "arg_types": {},
    },
    "purchase_order/search_open_by_sku": {
        "namespace": "purchase_order",
        "action": "search_open_by_sku",
        "module": "tools.workspace_tools",
        "function": "purchase_order_search_open_by_sku",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "purchase_order_list",
        "required_args": ["sku"],
        "optional_args": [],
        "arg_types": {},
    },
    "supplier_invoice/read": {
        "namespace": "supplier_invoice",
        "action": "read",
        "module": "tools.workspace_tools",
        "function": "supplier_invoice_read",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "supplier_invoice_record",
        "required_args": ["invoice_id"],
        "optional_args": [],
        "arg_types": {},
    },
    "test/echo": {
        "namespace": "test",
        "action": "echo",
        "module": "runtime.test_tools",
        "function": "echo",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "test_echo_result",
        "required_args": [],
        "optional_args": ["message", "event_id"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "order_context/build": {
        "namespace": "order_context",
        "action": "build",
        "module": "runtime.order_tools",
        "function": "order_context_build",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "order_context_build_result",
        "required_args": ["customer", "order", "shipment"],
        "optional_args": ["payment"],
        "arg_types": {},
        "dry_run_executes": True,
    },
    "gb/list": {
        "namespace": "gb",
        "action": "list",
        "module": "tools.gobook_tools",
        "function": "rpa_list",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_booking_list",
        "required_args": [],
        "optional_args": ["slowmo"],
        "arg_types": {"slowmo": "int"},
    },
    "gb/open_courts": {
        "namespace": "gb",
        "action": "open_courts",
        "module": "tools.gobook_tools",
        "function": "rpa_open_courts",
        "side_effect": False,
        "requires_approval": False,
        "allow_live": True,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_open_court_list",
        "required_args": ["date", "start", "end"],
        "optional_args": ["slowmo"],
        "arg_types": {"slowmo": "int"},
    },
    "gb/book": {
        "namespace": "gb",
        "action": "book",
        "module": "tools.gobook_tools",
        "function": "rpa_book",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_booking_result",
        "required_args": ["date", "time_value", "court"],
        "optional_args": ["confirm", "slowmo"],
        "arg_types": {"confirm": "bool", "slowmo": "int"},
    },
    "gb/cancel": {
        "namespace": "gb",
        "action": "cancel",
        "module": "tools.gobook_tools",
        "function": "rpa_cancel",
        "side_effect": True,
        "requires_approval": True,
        "allow_live": False,
        "allow_live_side_effect": False,
        "live_guardrail": "blocked",
        "output_type": "gobook_cancel_result",
        "required_args": ["date", "time_value", "court"],
        "optional_args": ["confirm", "slowmo"],
        "arg_types": {"confirm": "bool", "slowmo": "int"},
    },
}


BUILTIN_TOOL_REGISTRY = copy.deepcopy(TOOL_REGISTRY)


def build_tool_registry(include_external: bool = True, *, config_path: str | Path = "config/enabled_toolpacks.json") -> dict[str, dict]:
    registry = dict(BUILTIN_TOOL_REGISTRY)
    if include_external:
        from src.toolpack_loader import build_external_tool_registry

        external_registry = build_external_tool_registry(config_path=config_path)
        for key, spec in external_registry.items():
            if key in registry:
                raise ToolRegistryError(f"External tool cannot override built-in tool: {key}")
            registry[key] = spec
    return registry


TOOL_REGISTRY = build_tool_registry(include_external=True)


def tool_key(namespace: str, action: str) -> str:
    return f"{namespace}/{action}"


def get_tool_spec(namespace: str, action: str) -> dict:
    key = tool_key(namespace, action)
    try:
        return TOOL_REGISTRY[key]
    except KeyError as exc:
        raise ToolNotRegisteredError(f"Tool is not registered: {key}") from exc


def is_registered_tool(namespace: str, action: str) -> bool:
    return tool_key(namespace, action) in TOOL_REGISTRY


def validate_tool_args(tool_spec: dict, args: dict[str, object]) -> None:
    required_args = tool_spec.get("required_args", [])
    missing = [name for name in required_args if name not in args]
    if missing:
        raise ToolArgumentError(f"Missing required tool arguments: {', '.join(missing)}")


def coerce_tool_args(tool_spec: dict, args: dict[str, str]) -> dict[str, object]:
    coerced: dict[str, object] = {}
    arg_types = tool_spec.get("arg_types", {})
    for key, value in args.items():
        coercion_type = arg_types.get(key)
        if coercion_type == "int":
            coerced[key] = _coerce_int(key, value)
        elif coercion_type == "bool":
            coerced[key] = _coerce_bool(key, value)
        else:
            coerced[key] = value
    return coerced


def _coerce_int(key: str, value: object) -> int:
    if isinstance(value, bool):
        raise ToolArgumentError(f"Argument {key} must be an integer.")
    if isinstance(value, int):
        return value
    if not isinstance(value, str):
        raise ToolArgumentError(f"Argument {key} must be an integer.")
    try:
        return int(value)
    except ValueError as exc:
        raise ToolArgumentError(f"Argument {key} must be an integer.") from exc


def _coerce_bool(key: str, value: object) -> bool:
    if isinstance(value, bool):
        return value
    if not isinstance(value, str):
        raise ToolArgumentError(f"Argument {key} must be a boolean.")
    lowered = value.strip().lower()
    if lowered in {"true", "1", "yes", "on"}:
        return True
    if lowered in {"false", "0", "no", "off"}:
        return False
    raise ToolArgumentError(f"Argument {key} must be a boolean.")


def register_optional_absa_tools(registry: dict[str, dict] | None = None) -> None:
    if os.environ.get("ENABLE_OPTIONAL_RPA_TOOLS", "").strip().lower() not in {"1", "true", "yes", "on"}:
        return
    target = registry if registry is not None else TOOL_REGISTRY
    from optional_tools.rpa.google_messages_absa.registry import register_tools

    register_tools(target)


register_optional_absa_tools()
