from __future__ import annotations

from typing import Any, Protocol


class PersistenceBackend(Protocol):
    backend_name: str

    def save_taskframe(self, frame: dict[str, Any]) -> None: ...
    def load_taskframe(self, frame_id: str) -> dict[str, Any] | None: ...
    def list_taskframes(self, limit: int = 100) -> list[dict[str, Any]]: ...

    def append_event(self, event: dict[str, Any]) -> None: ...
    def get_event(self, event_id: str) -> dict[str, Any] | None: ...
    def list_events(self, limit: int = 100) -> list[dict[str, Any]]: ...

    def save_queue_record(self, record: dict[str, Any]) -> None: ...
    def get_queue_record(self, event_id: str) -> dict[str, Any] | None: ...
    def list_queue_records(self, limit: int = 100, **filters: Any) -> list[dict[str, Any]]: ...

    def save_durable_queue_record(self, record: dict[str, Any]) -> None: ...
    def get_durable_queue_record(self, queue_id: str) -> dict[str, Any] | None: ...
    def list_durable_queue_records(self, limit: int = 100, **filters: Any) -> list[dict[str, Any]]: ...

    def append_run_ledger_record(self, record: dict[str, Any]) -> None: ...
    def list_run_ledger_records(self, limit: int = 100) -> list[dict[str, Any]]: ...

    def save_schedule_record(self, record: dict[str, Any]) -> None: ...
    def get_schedule_record(self, schedule_id: str) -> dict[str, Any] | None: ...
    def list_schedule_records(self, limit: int = 200, **filters: Any) -> list[dict[str, Any]]: ...

    def save_schedule_run_record(self, record: dict[str, Any]) -> None: ...
    def list_schedule_run_records(self, limit: int = 100, **filters: Any) -> list[dict[str, Any]]: ...

    def health(self) -> dict[str, Any]: ...
